config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks',
    registrations: 'users/registrations'
  }
  get 'movies/index'
  root to: "movies#index"

  resources :movies do
    resources :comments,only: [:create,:destroy]
    resources :likes,only: [:create]
    delete '/likes(.:format)',to: "likes#destroy"
    collection do
     get 'likes/show'
    end

    collection do
      get 'search'
    end
    
  end

  resources :users, only: [:show,:edit,:update]

  

  resources :users do
     resource :follow
     resources :followings
     resources :followers
     get 'chat/:id' => 'chats#show', as: 'chat'
     get '/chats', to: 'chats#index'
     resources :chats, only: [:create]
  end

end

app/models/user.rb
class User < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,:omniauthable, omniauth_providers: [:google_oauth2]

  with_options presence: true do
    validates :nickname
    validates :instrument
    validates :prefecture_id,numericality: { other_than: 0,message: 'を選択してください' }
    validates :history_id,numericality: { other_than: 0,message: 'を選択してください' }
    validates :age, format:{with: /\A[0-9]+\z/,message:'を半角数字のみで入力してください'}
    validates :password, format: { with: /(?=.*[a-zA-Z])(?=.*\d)[a-zA-Z\d]/, message: 'を全て半角で英数字を混ぜて設定してください' }
  end
    
    has_many :movies
    belongs_to :prefecture
    belongs_to :history
    belongs_to :gender
    has_many :comments
    has_many :likes, dependent: :destroy

    has_many :user_rooms
    has_many :chats
    has_many :rooms, through: :user_rooms
    has_many :active_relationships,class_name: 'Follow', foreign_key: 'user_id'
    has_many :passive_relationships,class_name: 'Follow', foreign_key: 'target_user_id'
    has_many :followings, through: :active_relationships, source: :target_user
    has_many :followers, through: :passive_relationships, source: :user
    has_many :sns_credentials

      def already_liked?(movie)
        self.likes.exists?(movie_id: movie.id)
      end

      def self.from_omniauth(auth)
        sns = SnsCredential.where(provider: auth.provider, uid: auth.uid).first_or_create
        user = User.where(email: auth.info.email).first_or_initialize(
          nickname: auth.info.name,
            email: auth.info.email
        )

        if user.persisted?
          sns.user = user
          sns.save
        end
        { user: user, sns: sns }

      end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController

  def google_oauth2
    authorization
   end
  
   private
  
   def authorization
     sns_info = User.from_omniauth(request.env["omniauth.auth"])
     @user=sns_info[:user]

     if @user.persisted? 
      sign_in_and_redirect @user, event: :authentication
    else 
      @sns_id=sns_info[:sns].id
      render template: 'devise/registrations/new'
    end

   end
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  def create
    if params[:sns_auth] == 'true'
      pass = Devise.friendly_token
      params[:user][:password] = pass
      params[:user][:password_confirmation] = pass
    end
    super
  end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
before_action :edit_user,only: [:edit,:update]

  def show
    user = User.find(params[:id])
    @user=user
    @movies = user.movies.order(created_at: :desc)
  end

  def edit
    @user=User.find(params[:id])
  end

  def update
    @user=User.find(params[:id])
    if current_user.update(user_params)
      sign_in(current_user, bypass: true)
      redirect_to root_path
    else
      redirect_to "/users/#{current_user.id}/edit"
    end
  end

  private

  def user_params
    params.require(:user).permit(:email,:password,:nickname,:instrument,:prefecture_id,:history_id,:gender_id,:age,:genre,:artist)
  end

  def edit_user
    @user=User.find(params[:id])
    if user_signed_in? && current_user.id != @user.id
      redirect_to root_path
    end
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
   
   <%= form_for(current_user) do |f| %>

   <div class="field">
    <%= f.label :email %><br />
    <%= f.email_field :email, autofocus: true, autocomplete: "email" %>
  </div>

  <div class="field">
    <%= f.label :password %>
    <% if @minimum_password_length %>
    <em>(<%= @minimum_password_length %> characters minimum)</em>
    <% end %><br />
    <%= f.password_field :password, autocomplete: "new-password" %>
  </div>

  <div class="field">
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation, autocomplete: "new-password" %>
  </div>

  <div class="field">
    <%= f.label :nickname %><br />
    <%= f.text_area :nickname,autocomplete: "nickname" %>
  </div>

  <div class="field">
    <%= f.label :instrument %><br />
    <%= f.text_area :instrument, autocomplete: "instrument" %>
  </div>
  
  <div class="field">
    <%= f.label :prefecture_id %><br />
    <%= f.collection_select(:prefecture_id, Prefecture.all, :id, :name, {}, {class:"select-box", id:"user-prefecture"}) %>
  </div>

  <div class="field">
    <%= f.label :history_id %><br />
    <%= f.collection_select(:history_id, History.all, :id, :name, {}, {class:"select-box", id:"user-history"}) %>
  </div>

  <div class="field">
    <%= f.label :gender_id %><br />
    <%= f.collection_select(:gender_id, Gender.all, :id, :name, {}, {class:"select-box", id:"user-gender"}) %>
  </div>
  
  <div class="field">
    <%= f.label :age %><br />
    <%= f.text_area :age, autocomplete: "age" %>
  </div>

  <div class="field">
    <%= f.label :genre %><br />
    <%= f.text_area :genre, autocomplete: "genre" %>
  </div>

  <div class="field">
    <%= f.label :artist %><br />
    <%= f.text_area :artist, autocomplete: "artist" %>
  </div>

  <div class="actions">
    <%= f.submit "更新する",class:"button is-primary m-4" %>
  </div>
<% end %>

app/views/users/show.html.erb
  <h1 class="title-list">
  【<%= @user.nickname%>】さんの個人ページ
  </h1>
  
  <%= link_to 'ホームに戻る', root_path, class:"button home_return" %>


  <div class="tabs">
  <ul>
    <li>
    <%= link_to  'フォロー', [@user,:followings] ,class:"button m-1"%>
    </li>
    <li>
      <%= link_to 'フォロワー', [@user,:followers] ,class:"button m-1"%>
    </li>
  
    <% if user_signed_in? && current_user != @user %>
      <% if current_user.active_relationships.exists?(target_user_id: @user.id) %>
        <li>
          <%= link_to 'フォロー解除', [@user, :follow], method: :delete ,class:"button m-1"%>
        </li>
      <% else %>
        <li>
          <%= link_to 'フォローする', [@user, :follow], method: :post,class:"button m-1" %>
        </li>
      <% end %>
    <% end %>
  </ul>
  </div>

<div class="card user_show pl-4">
  <br>
    <span>ニックネーム：</span><%= @user.nickname %>
  <br>
    <span>活動エリア：</span><%= @user.prefecture.name %>
  <br>
    <span>楽器歴：</span><%= @user.history.name %>
  <br>
    <span>性別：</span><%= @user.gender.name %>
  <br>
    <span>年齢：</span><%= @user.age %>
  <br>
    <span>好きなジャンル：</span><%= @user.genre %>
  <br>
    <span>好きなアーティスト：</span><%= @user.artist %>
  <br>
  <br>

  <% if current_user != @user %>
  <%= link_to 'DMを送信する', user_chat_path(@user.id) ,class:"button"%>
  <% end %> 


     <ul class="more_list">
        <% if user_signed_in? && current_user.id == @user.id %>
          <li>
            <%= link_to '個人ページ編集', edit_user_path(@user.id), method: :get ,class:"button" %>
          </li>
        <% end %> 
     </ul>
     <br>
     <br>

</div>



<div class="contents row">
  <div class="user_post_list">
  <p>【<%= @user.nickname %>】さんの投稿一覧</p>
  </div>
  <% @movies.each do |movie| %>
    <%= render partial:"movies/movie",locals: {movie: movie}%>
  <% end %>
</div>