config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks',
    registrations: 'users/registrations'
  }
  get 'movies/index'
  root to: "movies#index"

  resources :movies do
    resources :comments,only: [:create,:destroy]
    resources :likes,only: [:create]
    delete '/likes(.:format)',to: "likes#destroy"
    collection do
     get 'likes/show'
    end

    collection do
      get 'search'
    end
    
  end

  resources :users, only: [:show,:edit,:update]

  

  resources :users do
     resource :follow
     resources :followings
     resources :followers
     get 'chat/:id' => 'chats#show', as: 'chat'
     get '/chats', to: 'chats#index'
     resources :chats, only: [:create]
  end

end

app/models/chat.rb
class Chat < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :movie
end

app/models/follow.rb
class Follow < ApplicationRecord
  belongs_to :user
  belongs_to :target_user, class_name: 'User',foreign_key: 'target_user_id'
end

app/models/gender.rb
class Gender < ActiveHash::Base
  self.data = [
    { id: 0, name: '--' },
    { id: 1, name: '男性' },
    { id: 2, name: '女性' },
    { id: 3, name: 'その他' },
  ]

  include ActiveHash::Associations
  has_many :users
end

app/models/history.rb
class History < ActiveHash::Base
  self.data = [
    { id: 0, name: '--' },
    { id: 1, name: '１年未満' },
    { id: 2, name: '１年以上３年未満' },
    { id: 3, name: '４年以上' },
    { id: 4, name: '上級者' },
  ]

  include ActiveHash::Associations
  has_many :users
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :movie

  validates_uniqueness_of :movie_id,scope: :user_id
end

app/models/movie.rb
class Movie < ApplicationRecord
 
  with_options presence: true do
    validates :text
    validates :instrument
  end

  mount_uploader :video_top ,VideoTopUploader
  validates :video_top, presence: true


  # has_one_attached :video_top
  belongs_to :user
  has_many :comments,dependent: :destroy
  has_many :likes, dependent: :destroy



end

app/models/prefecture.rb
class Prefecture < ActiveHash::Base
  self.data = [
    {id: 0, name: '--'}, {id: 1, name: '北海道'}, {id: 2, name: '青森県'}, 
    {id: 3, name: '岩手県'}, {id: 4, name: '宮城県'}, {id: 5, name: '秋田県'}, 
    {id: 6, name: '山形県'}, {id: 7, name: '福島県'}, {id: 8, name: '茨城県'}, 
    {id: 9, name: '栃木県'}, {id: 10, name: '群馬県'}, {id: 11, name: '埼玉県'}, 
    {id: 12, name: '千葉県'}, {id: 13, name: '東京都'}, {id: 14, name: '神奈川県'}, 
    {id: 15, name: '新潟県'}, {id: 16, name: '富山県'}, {id: 17, name: '石川県'}, 
    {id: 18, name: '福井県'}, {id: 19, name: '山梨県'}, {id: 20, name: '長野県'}, 
    {id: 21, name: '岐阜県'}, {id: 22, name: '静岡県'}, {id: 23, name: '愛知県'}, 
    {id: 24, name: '三重県'}, {id: 25, name: '滋賀県'}, {id: 26, name: '京都府'}, 
    {id: 27, name: '大阪府'}, {id: 28, name: '兵庫県'}, {id: 29, name: '奈良県'}, 
    {id: 30, name: '和歌山県'}, {id: 31, name: '鳥取県'}, {id: 32, name: '島根県'}, 
    {id: 33, name: '岡山県'}, {id: 34, name: '広島県'}, {id: 35, name: '山口県'}, 
    {id: 36, name: '徳島県'}, {id: 37, name: '香川県'}, {id: 38, name: '愛媛県'}, 
    {id: 39, name: '高知県'}, {id: 40, name: '福岡県'}, {id: 41, name: '佐賀県'}, 
    {id: 42, name: '長崎県'}, {id: 43, name: '熊本県'}, {id: 44, name: '大分県'}, 
    {id: 45, name: '宮崎県'}, {id: 46, name: '鹿児島県'}, {id: 47, name: '沖縄県'}
              ]
    include ActiveHash::Associations
    has_many :users
    
end

app/models/room.rb
class Room < ApplicationRecord
  has_many :chats
  has_many :user_rooms
end

app/models/sns_credential.rb
class SnsCredential < ApplicationRecord
  belongs_to :user,optional: true
end

app/models/user.rb
class User < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,:omniauthable, omniauth_providers: [:google_oauth2]

  with_options presence: true do
    validates :nickname
    validates :instrument
    validates :prefecture_id,numericality: { other_than: 0,message: 'を選択してください' }
    validates :history_id,numericality: { other_than: 0,message: 'を選択してください' }
    validates :age, format:{with: /\A[0-9]+\z/,message:'を半角数字のみで入力してください'}
    validates :password, format: { with: /(?=.*[a-zA-Z])(?=.*\d)[a-zA-Z\d]/, message: 'を全て半角で英数字を混ぜて設定してください' }
  end
    
    has_many :movies
    belongs_to :prefecture
    belongs_to :history
    belongs_to :gender
    has_many :comments
    has_many :likes, dependent: :destroy

    has_many :user_rooms
    has_many :chats
    has_many :rooms, through: :user_rooms
    has_many :active_relationships,class_name: 'Follow', foreign_key: 'user_id'
    has_many :passive_relationships,class_name: 'Follow', foreign_key: 'target_user_id'
    has_many :followings, through: :active_relationships, source: :target_user
    has_many :followers, through: :passive_relationships, source: :user
    has_many :sns_credentials

      def already_liked?(movie)
        self.likes.exists?(movie_id: movie.id)
      end

      def self.from_omniauth(auth)
        sns = SnsCredential.where(provider: auth.provider, uid: auth.uid).first_or_create
        user = User.where(email: auth.info.email).first_or_initialize(
          nickname: auth.info.name,
            email: auth.info.email
        )

        if user.persisted?
          sns.user = user
          sns.save
        end
        { user: user, sns: sns }

      end
end

app/models/user_room.rb
class UserRoom < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

app/helpers/chats_helper.rb
module ChatsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/followers_helper.rb
module FollowersHelper
end

app/helpers/followings_helper.rb
module FollowingsHelper
end

app/helpers/follows_helper.rb
module FollowsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
  def movie_lists(movies)
    html = ''
    movies.each do |movie|
      html += render(partial: 'movie',locals: { movie: movie })
    end
    return raw(html)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_error_messages.html.erb
<% if model.errors.any? %>
<div class="error-alert">
 <ul>
   <% model.errors.full_messages.each do |message| %>
   <li class='error-message'><%= message %></li>
   <% end %>
 </ul>
</div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html >
  <head>
    <title>MusicJam</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta charset="UTF-8">
    <link rel="stylesheet" type="text/css" href="http://yui.yahooapis.com/3.18.1/build/cssreset/cssreset-min.css">
    <%# <link rel="stylesheet" type="text/css" href="style.css"> %>
    <%= stylesheet_link_tag 'application', media: 'all'%>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://kit.fontawesome.com/a172a2ef25.js" crossorigin="anonymous"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    
    <style>
    
    
    .tabs ul{
      flex-grow: 0;
      border-bottom-width: 0px;
    }

    .jam_top {
      font-family: Comic Sans MS,'cursive';
      color: white;
      cursor: pointer;
      justify-content: center;
      display: flex;
      font-size: 25px;
    }
    .card {
    background-color: white;
    border-radius: 0.25rem;
    box-shadow: 0 0.5em 1em -0.125em rgb(10 10 10 / 10%), 0 0px 0 1px rgb(10 10 10 / 2%);
    color: #4a4a4a;
    position: relative;
    margin-top:60px;
    max-width: 500px;
    min-width: 500px;
    padding: 8px;
    }

    figure.movie {
    display: flex;
    justify-content: center;
}

    .like_lists {
    font-size: 25px;
    display: flex;
    }

    

    i.far.fa-heart {
    color: hotpink;
    font-size: 25px;
    } 

    ::before {
    color: hotpink;
    font-size: 25px;
    }

    a.button {
    margin: 1px;
    }

    .columns.is-centered {
    display: flex;
    }

    label.intrument_label {
    color: white;
    }

    .card.user_show.pl-4 {
    color: white;
    background: black;
    /* min-width: 100%; */
    width: 400px;
    max-width: 100%;
    }

    a.follows_name_class {
    font-size: 25px;
    display: flex;
    justify-content: center;
    }
    
    span.name {
    font-size: 20px;
}

    a.button.home_return {
    position: fixed;
    z-index: 1;
    right: 10%;
    top: 15px;
    }

    body, div, dl, dt, dd, ul, ol, li, h1, h2, h3, h4, h5, h6, pre, code, form, fieldset, legend, input, textarea, p, blockquote, th, td {
    margin: auto;
    padding: 0;
}

    .card.container.mt-3 {
    padding: 15px;
    max-width: 40%;
    }

    .user_post_list{
    display: flex;
    justify-content: center;
    font-size: 25px;
    margin-top:60px;
    }

    a.follows_name{
      color:black;
    }

    .weight-bold-text {
    width: 400px;
    }

    table.message.table {
    min-width: 400px;
    }
    input#chat_message {
    width: 300px;
    height: 30px;
    margin: 20px;
    }

    .google_login {
    margin: 10px 0;
    }
    
    </style>
  </head>

  <body>

    

    <section class="section">
      <div class="columns is-centered">
        <div class="coloumn is-5">
          <%= yield %>
        </div>
      </div>
    </section>
_
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if model.errors.any? %>
<div class="error-alert">
  <ul>
    <% model.errors.full_messages.each do |message| %>
    <li class='error-message'><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

app/views/shared/_footer.html.erb
 <div class="tabs">
  <% if user_signed_in?%>
  
    <ul>
      <li><a class="button m-1" href="/movies/new">
        <span class="movies-btn_text">投稿</span></a></li>
        
      <li><a class="button m-1 like" href="/movies/likes/show">
        <span class="mlikes-btn_text">いいね一覧</span></a></li>
        
      <li><a class="button m-1" href="/users/<%=current_user.id%>/chats">
        <span class="mlikes-btn_text">DM</span></a></li>
    </ul>
  
  <% else%>
  <p class="sign_in_info">投稿.DM送信をするにはユーザーアカウントを作成及びサインインしましょう</p>
  <% end %>
  
  <div class="search-btn-class">
   <%= search_form_for @m, url: search_movies_path  do |f| %>
      <%= f.label :instrument_eq, '楽器名',class:"intrument_label"%>
      <%= f.collection_select :instrument_eq, @movies, :instrument,:instrument, include_blank: '指定なし'%>
      <%=f.submit '検索',class:"button is-primary" %>
    <% end %>
  </div>

  </div>

app/views/shared/_header.html.erb
    <div class="tabs">
      <% if user_signed_in? %>
      <ul>
        <li>
          <%= link_to 'フォロー', [current_user,:followings] ,class:"button m-1"%>
        </li>
        <li>
          <%= link_to 'フォロワー', [current_user,:followers] ,class:"button m-1"%>
        </li>
      </ul>
      <% end %>
    
      <ul class='lists-right'>
        <% if user_signed_in? %>
         <li><%= link_to current_user.nickname, user_path(current_user.id), class: "user-nickname",class:"button m-1"%></li> 
         <li><%= link_to 'ログアウト', destroy_user_session_path , method: :delete, class: "logout",class:"button m-1"%></li> 
        <% else %>
        <li><%= link_to 'ログイン', new_user_session_path , class: "login" ,class:"button m-1"%></li>
        <li><%= link_to '新規登録',  new_user_registration_path , class: "sign-up" ,class:"button m-1"%></li>
        <% end %>
      </ul>
  

    
    </div>