config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks',
    registrations: 'users/registrations'
  }
  get 'movies/index'
  root to: "movies#index"

  resources :movies do
    resources :comments,only: [:create,:destroy]
    resources :likes,only: [:create]
    delete '/likes(.:format)',to: "likes#destroy"
    collection do
     get 'likes/show'
    end

    collection do
      get 'search'
    end
    
  end

  resources :users, only: [:show,:edit,:update]

  

  resources :users do
     resource :follow
     resources :followings
     resources :followers
     get 'chat/:id' => 'chats#show', as: 'chat'
     get '/chats', to: 'chats#index'
     resources :chats, only: [:create]
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
  
end

app/models/chat.rb
class Chat < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :movie
end

app/models/follow.rb
class Follow < ApplicationRecord
  belongs_to :user
  belongs_to :target_user, class_name: 'User',foreign_key: 'target_user_id'
end

app/models/gender.rb
class Gender < ActiveHash::Base
  self.data = [
    { id: 0, name: '--' },
    { id: 1, name: '男性' },
    { id: 2, name: '女性' },
    { id: 3, name: 'その他' },
  ]

  include ActiveHash::Associations
  has_many :users
end

app/models/history.rb
class History < ActiveHash::Base
  self.data = [
    { id: 0, name: '--' },
    { id: 1, name: '１年未満' },
    { id: 2, name: '１年以上３年未満' },
    { id: 3, name: '４年以上' },
    { id: 4, name: '上級者' },
  ]

  include ActiveHash::Associations
  has_many :users
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :movie

  validates_uniqueness_of :movie_id,scope: :user_id
end

app/models/movie.rb
class Movie < ApplicationRecord
 
  with_options presence: true do
    validates :text
    validates :instrument
  end

  mount_uploader :video_top ,VideoTopUploader
  validates :video_top, presence: true


  # has_one_attached :video_top
  belongs_to :user
  has_many :comments,dependent: :destroy
  has_many :likes, dependent: :destroy



end

app/models/prefecture.rb
class Prefecture < ActiveHash::Base
  self.data = [
    {id: 0, name: '--'}, {id: 1, name: '北海道'}, {id: 2, name: '青森県'}, 
    {id: 3, name: '岩手県'}, {id: 4, name: '宮城県'}, {id: 5, name: '秋田県'}, 
    {id: 6, name: '山形県'}, {id: 7, name: '福島県'}, {id: 8, name: '茨城県'}, 
    {id: 9, name: '栃木県'}, {id: 10, name: '群馬県'}, {id: 11, name: '埼玉県'}, 
    {id: 12, name: '千葉県'}, {id: 13, name: '東京都'}, {id: 14, name: '神奈川県'}, 
    {id: 15, name: '新潟県'}, {id: 16, name: '富山県'}, {id: 17, name: '石川県'}, 
    {id: 18, name: '福井県'}, {id: 19, name: '山梨県'}, {id: 20, name: '長野県'}, 
    {id: 21, name: '岐阜県'}, {id: 22, name: '静岡県'}, {id: 23, name: '愛知県'}, 
    {id: 24, name: '三重県'}, {id: 25, name: '滋賀県'}, {id: 26, name: '京都府'}, 
    {id: 27, name: '大阪府'}, {id: 28, name: '兵庫県'}, {id: 29, name: '奈良県'}, 
    {id: 30, name: '和歌山県'}, {id: 31, name: '鳥取県'}, {id: 32, name: '島根県'}, 
    {id: 33, name: '岡山県'}, {id: 34, name: '広島県'}, {id: 35, name: '山口県'}, 
    {id: 36, name: '徳島県'}, {id: 37, name: '香川県'}, {id: 38, name: '愛媛県'}, 
    {id: 39, name: '高知県'}, {id: 40, name: '福岡県'}, {id: 41, name: '佐賀県'}, 
    {id: 42, name: '長崎県'}, {id: 43, name: '熊本県'}, {id: 44, name: '大分県'}, 
    {id: 45, name: '宮崎県'}, {id: 46, name: '鹿児島県'}, {id: 47, name: '沖縄県'}
              ]
    include ActiveHash::Associations
    has_many :users
    
end

app/models/room.rb
class Room < ApplicationRecord
  has_many :chats
  has_many :user_rooms
end

app/models/sns_credential.rb
class SnsCredential < ApplicationRecord
  belongs_to :user,optional: true
end

app/models/user.rb
class User < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,:omniauthable, omniauth_providers: [:google_oauth2]

  with_options presence: true do
    validates :nickname
    validates :instrument
    validates :prefecture_id,numericality: { other_than: 0,message: 'を選択してください' }
    validates :history_id,numericality: { other_than: 0,message: 'を選択してください' }
    validates :age, format:{with: /\A[0-9]+\z/,message:'を半角数字のみで入力してください'}
    validates :password, format: { with: /(?=.*[a-zA-Z])(?=.*\d)[a-zA-Z\d]/, message: 'を全て半角で英数字を混ぜて設定してください' }
  end
    
    has_many :movies
    belongs_to :prefecture
    belongs_to :history
    belongs_to :gender
    has_many :comments
    has_many :likes, dependent: :destroy

    has_many :user_rooms
    has_many :chats
    has_many :rooms, through: :user_rooms
    has_many :active_relationships,class_name: 'Follow', foreign_key: 'user_id'
    has_many :passive_relationships,class_name: 'Follow', foreign_key: 'target_user_id'
    has_many :followings, through: :active_relationships, source: :target_user
    has_many :followers, through: :passive_relationships, source: :user
    has_many :sns_credentials

      def already_liked?(movie)
        self.likes.exists?(movie_id: movie.id)
      end

      def self.from_omniauth(auth)
        sns = SnsCredential.where(provider: auth.provider, uid: auth.uid).first_or_create
        user = User.where(email: auth.info.email).first_or_initialize(
          nickname: auth.info.name,
            email: auth.info.email
        )

        if user.persisted?
          sns.user = user
          sns.save
        end
        { user: user, sns: sns }

      end
end

app/models/user_room.rb
class UserRoom < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

app/controllers/chats_controller.rb
class ChatsController < ApplicationController
  before_action :authenticate_user!

  def show
    @user= User.find(params[:id])
    rooms=current_user.user_rooms.pluck(:room_id)
    user_rooms= UserRoom.find_by(user_id: @user.id,room_id: rooms)

    if user_rooms.nil?
      @room=Room.new
      @room.save

      UserRoom.create(user_id: @user.id, room_id: @room.id)
      UserRoom.create(user_id: current_user.id, room_id: @room.id)
    else
      @room = user_rooms.room
    end

    @chats=@room.chats
    @chat=Chat.new(room_id: @room.id)
  end

  def create
    @chat=current_user.chats.new(chat_params)
    if @chat.save
      ActionCable.server.broadcast 'chat_channel',content: @chat
    end
  end

  def index
   
    user_rooms=UserRoom.where(user_id: params[:user_id])
    a=[]
    user_rooms.each do |user_room|
      a.push(user_room.room_id)
    end

    b=[]
    a.each do |r_id|
    chat_user=UserRoom.where(room_id: r_id).where.not(user_id: params[:user_id])
    b.push(chat_user)
    end
    
    
    array_nums=b.size
    c=[]
    array_nums.times do |num|
    chat_user_ids=b[num][0].user_id
    c.push(chat_user_ids)
    end
    
    d=[]
    c.each do|user_id|
    user=User.find(user_id)
    d.push(user)
    end

    @dm_chat_users=d

  end

  private
  def chat_params
      params.require(:chat).permit(:message, :room_id)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/chats_helper.rb
module ChatsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/followers_helper.rb
module FollowersHelper
end

app/helpers/followings_helper.rb
module FollowingsHelper
end

app/helpers/follows_helper.rb
module FollowsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
  def movie_lists(movies)
    html = ''
    movies.each do |movie|
      html += render(partial: 'movie',locals: { movie: movie })
    end
    return raw(html)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/chats/create.js.erb
<%# $('.message').append("<p style='text-align: left;'><%= @chat.message</p>"); %> 
<%# $('input[type=text]').val("") %>

app/views/chats/index.html.erb
<h1 class="title-list">
<p>ダイレクトメッセージ 相手一覧</p>
</h1>
<%= link_to 'ホームに戻る', root_path, class:"button home_return" %>
<%@dm_chat_users.each do |dm_chat_user| %>
<div class="dm_user">
<a href="/users/<%= dm_chat_user.id%>/chat/<%= dm_chat_user.id %>"> 
<%= dm_chat_user.nickname %>
</a>
</div>
<% end %>

app/views/chats/show.html.erb
<%= link_to 'ホームに戻る', root_path, class:"button home_return" %>
<div class="container">
    <div class="row">
        <div class="col-xs-6">
            <h2 id="room" data-room="<%= @room.id %>" data-user="<%= current_user.id %>"><%= @user.nickname %> さんとのダイレクトメッセージ</h2>

            

            <%= form_with model: @chat,url: user_chats_path do |f| %>
              <%= f.text_field :message %>
              <%= f.hidden_field :room_id %>
              <%= f.submit '送信', class:"submit-btn"%>
            <% end %>

            <table class="message table">
              <thead>
                <tr>
                  <th style="text-align: left; font-size: 20px;"><%= current_user.nickname %></th>
                  <th style="text-align: right; font-size: 20px;"><%= @user.nickname %></th>
                </tr>
              </thead>

            <tbody id="chat_left_text">
              <% @chats.reverse_each do |chat| %>
                <% if chat.user_id == current_user.id %>
                  <tr>
                    <th>
                      <p style="text-align: left;"><%= chat.message %></p>
                        </th>
                        <th></th>
                       </tr>
                <% else %>
                  <tr>
                    <th></th>
                    <th>
                      <p style="text-align: right;"><%= chat.message %></p>
                    </th>
                  </tr>
                  <% end %>
              <% end %>
            </tbody>
            
            </table>
        </div>
    </div>
</div>